### PR TITLE
Fix github link

### PR DESCRIPTION
**Pull request by danisal**
- Remove duplicated image

### CODE REVIEW

**Comment by huguestennier** [comment]
@danisal the repo value is expecting a repo in particular, not just the organization. Could you update it with a repo?

**Comment by danisal** [comment]
My mistake @huguestennier, already fixed

**Comment by danisal** [comment]
Is everything ok with the PR? Or does it need some more changes?

**Comment by huguestennier** [comment]
Hi! We're in the process of moving this repo under https://jamstack.org/headless-cms/

I'll transfer the PR and will merge soon

**Comment by huguestennier** [comment]
Updated on jamstack.org via https://github.com/jamstack/jamstack.org/pull/420 !

**Pull request closed without merging**
