### PR TITLE
Add Strapi

### PR DESCRIPTION
**Pull request by pierreburgy**

### CODE REVIEW

**Comment by erquhart** [comment]
Super cool project, going to be watching this one. Thanks for adding!

**Comment by raisedadead** [comment]
Strapi does not seem to be headless to me, from the docs. Is it still valid to add is as a resource? Please note I am just confused, not biased.

**Comment by erquhart** [comment]
Headless just means the CMS doesn't build your site, it just edits content. There's generally two categories - API driven, where your content is stored in a database somewhere and pulled into your site via API calls, and Git based, where your content is edited directly in your site's Git repository. Strapi is of the former type, API driven.

**Comment by pierreburgy** [comment]
Thank you @erquhart for the clarification!

**Comment by raisedadead** [comment]
@erquhart ah.. thanks that makes sense. thanks for clarifying, I was under the impression with "headless" being, does not need a server like netlifycms.

Anyways, apologies for the dumb question and thanks again.

**Pull request merged**
