### PR TITLE
Create tritan-cms.md

### PR DESCRIPTION
**Pull request by parkerj**
New project: TriTan CMS

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks @parkerj!

The readme warning that it isn't production ready until 1.0, and the lack of commits in the last six months, makes it feel like this isn't ready to be recommended. Any updates in the pipeline?

**Comment by parkerj** [comment]
Yes, lots of updates. It is stable and production ready even though not recommended for production yet. I will come back once is is tagged 1.0.

**Comment by erquhart** [comment]
I'll go ahead and merge, just wanted to make sure it was still moving.

**Comment by erquhart** [comment]
Hmm actually one more question: why is it described as "nearly headless"?

**Comment by parkerj** [comment]
You can use TriTan CMS as a traditional CMS (like WordPress, Drupal, etc.), as fully headless or nearly headless. Another way to say, nearly headless is "headless ready." Which means you start out using the CMS in the traditional sense but later on you realize that you need to support an iOS or Android app. Therefore, it is headless ready. I came across this term years ago in an article written by Mark Llobrera entitled, [The Nearly-Headless CMS](https://alistapart.com/column/nearly-headless-cms).

**Comment by erquhart** [comment]
Alright, fair enough :) Thanks for adding!

**Pull request merged**
