### PR TITLE
Edited Strapi description to better describe Strapi

### PR DESCRIPTION
**Pull request by davidkartuzinski**
Clarified various parts of Strapi and added a few points explaining what Strapi does as a headless CMS. Added a link to the Getting Started Docs to make it easier for users to find.

### CODE REVIEW

**Comment by davidkartuzinski** [comment]
@erquhart - Please let me know if anything is needed on this?

**Comment by erquhart** [comment]
Looks great, sorry for the delay! Also, hats off to you and the team for your incredible work on Strapi, looks to be growing fast!!

**Comment by davidkartuzinski** [comment]
> Looks great, sorry for the delay! Also, hats off to you and the team for your incredible work on Strapi, looks to be growing fast!!

Thank you Shawn.  I am a big fan of Netlify also... We just uploaded another with Netlify front and center!

**Comment by erquhart** [comment]
Nice! Let me know if you have a link I can share with the team 👍👍

**Pull request merged**
