### PR TITLE
Add IBM Watson Content Hub CMS

### PR DESCRIPTION
**Pull request by will-izard**

### CODE REVIEW

**Comment by biilmann** [comment]
Sounds like the `type` should be `API Driven`?

**Comment by will-izard** [comment]
Hi. Thanks for the quick response. Wasn't sure if you could put anything in the field, or what the options are. I'd say it is more "Business user experience driven, but with great API support too", but that's quite long....

**Comment by will-izard** [comment]
Still, happy to do that if it helps

**Comment by calavera** [comment]
LGTM

**Pull request merged**
