### PR TITLE
Create bloomreach.md

### PR DESCRIPTION
**Pull request by niklaswinkels**
Adding Bloomreach CMS page with images

### CODE REVIEW

**Comment by niklaswinkels** [comment]
hi @erquhart - i wanted to add bloomreach to the list, any chance you could take a look? :)

**Comment by erquhart** [comment]
Looks good 👍

**Comment by niklaswinkels** [comment]
thanks, @erquhart 🙌 looks like the deploy failed though https://app.netlify.com/sites/headlesscms/deploys

**Comment by erquhart** [comment]
I would assume it's because it says it's open source but has no GH repo, but the latest deploy succeeded so 🤷‍♀️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
