### PR TITLE
feat: Add NestJS.

### PR DESCRIPTION
**Pull request by ceefour**

### CODE REVIEW

**Comment by ledenis** [comment]
@ceefour @philhawksworth Isn't Nestjs a Node.js framework? Why add it as a headless CMS?

Am I missing something?

**Comment by ceefour** [comment]
@ledenis Yes it's a Node.js framework but it's more comparable to Strapi than to Express.js or Fastify. Since it has extensive support for REST APIs and GraphQL which are essential in JAMstack (especially when combined with Gatsby). Also with [NestJS Admin](https://nestjs-admin.com/) users can get a pretty good UI for editing entities.

**Comment by ledenis** [comment]
@ceefour Ok, I didn't know NestJS Admin, thanks!

But for me, NestJS is still far from a headless CMS (like Strapi), rather it's a tool to build your own CMS I would say. You have to write some code, you cannot just install it and use it right away.

**Comment by philhawksworth** [comment]
Yeah the fact that Nest allows for exposing content APIs made me think this can be a useful part of the headless CMS and decoupled content ecosystem.

That's why I accepted the PR

**Comment by ledenis** [comment]
Ok, I guess we don't have the same definition of CMS :)

**Comment by erquhart** [comment]
I would agree with @ledenis, headlesscms.org is "a list of content management systems", which Nest.js is not. We've said the same to other frameworks in the past. If Nest.js is powering a CMS, such as NestJS Admin mentioned above, that would fit the bill.

**Comment by erquhart** [comment]
Going to go ahead and revert this, but as I said before, a CMS built on nest is more than welcome!

**Pull request merged**
